services:

  # =========================================================
  # Azure Storage Emulator
  # =========================================================
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: securedrop-azurite

    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --skipApiVersionCheck
      --location /data

    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

    volumes:
      - azurite-data:/data

    restart: unless-stopped


  # =========================================================
  # Antivirus
  # =========================================================
  clamav:
    image: clamav/clamav:1.5
    container_name: securedrop-clamav

    ports:
      - "127.0.0.1:3310:3310"

    volumes:
      - clamav-data:/var/lib/clamav

    restart: unless-stopped


  # =========================================================
  # SecureDrop Portal
  # =========================================================
  portal:
    build:
      context: .
      dockerfile: portal/Dockerfile

    image: securedrop-portal:local
    container_name: securedrop-portal

    ports:
      - "8080:8080"

    environment:
      SECUREDROP_AZURE_STORAGE_CONNECTION_STRING: >-
        DefaultEndpointsProtocol=http;
        AccountName=devstoreaccount1;
        AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
        BlobEndpoint=http://azurite:10000/devstoreaccount1;
        QueueEndpoint=http://azurite:10001/devstoreaccount1;
        TableEndpoint=http://azurite:10002/devstoreaccount1;

    depends_on:
      - azurite

    restart: unless-stopped


  # =========================================================
  # SecureDrop Scanner
  # =========================================================
  scanner:
    build:
      context: .
      dockerfile: scanner/Dockerfile

    image: securedrop-scanner:local
    container_name: securedrop-scanner

    environment:
      SECUREDROP_STORAGE_CONNECTION_STRING: >-
        DefaultEndpointsProtocol=http;
        AccountName=devstoreaccount1;
        AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;
        BlobEndpoint=http://azurite:10000/devstoreaccount1;
        QueueEndpoint=http://azurite:10001/devstoreaccount1;
        TableEndpoint=http://azurite:10002/devstoreaccount1;

      SCANNER_CLAMAV_HOST: clamav
      SCANNER_CLAMAV_PORT: 3310

    depends_on:
      - azurite
      - clamav

    restart: unless-stopped


volumes:
  azurite-data:
  clamav-data: