spring.application.name=SecureDrop

server.port=8080

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB


# =============================
# DEFAULT ENVIRONMENT
# =============================

spring.profiles.default=local


# =============================
# SECUREDROP STORAGE RESOURCES
# =============================

# Blob containers
securedrop.azure.storage.quarantine-container=quarantine
securedrop.azure.storage.clean-container=clean
securedrop.azure.storage.infected-container=infected

# Queue
securedrop.azure.storage.scan-queue-name=scan-requests

# Table
securedrop.azure.storage.metadata-table-name=filemetadata