spring.application.name=SecureDrop

# Server
server.port=8080

# File upload limits
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Azure Storage
securedrop.azure.storage.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
securedrop.azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME}
securedrop.azure.storage.scan-queue-name=${AZURE_SCAN_QUEUE_NAME}