# =============================
# AZURE STORAGE
# =============================
# Disable the local Azurite connection string in Azure
securedrop.storage.connection-string=

securedrop.storage.account-name=${AZURE_STORAGE_ACCOUNT_NAME}

# Azure Storage endpoints
securedrop.storage.blob-endpoint=https://${AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net
securedrop.storage.queue-endpoint=https://${AZURE_STORAGE_ACCOUNT_NAME}.queue.core.windows.net
securedrop.storage.table-endpoint=https://${AZURE_STORAGE_ACCOUNT_NAME}.table.core.windows.net

# Storage resources
securedrop.storage.scan-queue=scan-requests
securedrop.storage.metadata-table=filemetadata

securedrop.storage.clean-container=clean
securedrop.storage.infected-container=infected

# =============================
# CLAMAV
# =============================

scanner.clamav.host=${SCANNER_CLAMAV_HOST}
scanner.clamav.port=${SCANNER_CLAMAV_PORT}
scanner.clamav.connect-timeout=5000
scanner.clamav.read-timeout=30000