spring.application.name=securedrop-scanner

# Default profile for local development
spring.profiles.default=local

securedrop.storage.connection-string=UseDevelopmentStorage=true
securedrop.storage.scan-queue=scan-requests
securedrop.storage.metadata-table=filemetadata

securedrop.storage.clean-container=clean
securedrop.storage.infected-container=infected

scanner.poll-delay=5000

scanner.clamav.host=127.0.0.1
scanner.clamav.port=3310
scanner.clamav.connect-timeout=5000
scanner.clamav.read-timeout=30000